LOWQ2:TaggerTrackerTransportationPreML:requireBeamElectron = false
LOWQ2:TaggerTrackerTransportationPreML:beamE = 10.0
LOWQ2:TaggerTrackerTransportationPostML:requireBeamElectron = false
LOWQ2:TaggerTrackerTransportationPostML:beamE = 10.0
